[2024-02-12T21:05:27.535+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.weather_api_ready scheduled__2024-02-12T20:30:00+00:00 [queued]>
[2024-02-12T21:05:27.554+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.weather_api_ready scheduled__2024-02-12T20:30:00+00:00 [queued]>
[2024-02-12T21:05:27.555+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-02-12T21:05:27.585+0000] {taskinstance.py:2191} INFO - Executing <Task(HttpSensor): weather_api_ready> on 2024-02-12 20:30:00+00:00
[2024-02-12T21:05:27.598+0000] {standard_task_runner.py:60} INFO - Started process 199 to run task
[2024-02-12T21:05:27.605+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'weather_api_ready', 'scheduled__2024-02-12T20:30:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/Weather_dag.py', '--cfg-path', '/tmp/tmp_fzg05d5']
[2024-02-12T21:05:27.610+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask weather_api_ready
[2024-02-12T21:05:27.726+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.weather_api_ready scheduled__2024-02-12T20:30:00+00:00 [running]> on host 3bd3b2605e24
[2024-02-12T21:05:27.886+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T20:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T20:30:00+00:00'
[2024-02-12T21:05:27.893+0000] {http.py:130} INFO - Poking: /data/2.5/weather?q=Bangkok&appid=d69585a88935d2a759a90a77d406e260
[2024-02-12T21:05:28.435+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/sensors/http.py", line 148, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/sensors/http.py", line 132, in poke
    response = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 145, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 98, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `weather_conn_id` isn't defined
[2024-02-12T21:05:28.441+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=weather_api_ready, execution_date=20240212T203000, start_date=20240212T210527, end_date=20240212T210528
[2024-02-12T21:05:28.459+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task weather_api_ready (The conn_id `weather_conn_id` isn't defined; 199)
[2024-02-12T21:05:28.502+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-12T21:05:28.572+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-12T21:13:12.521+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.weather_api_ready scheduled__2024-02-12T20:30:00+00:00 [queued]>
[2024-02-12T21:13:12.533+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.weather_api_ready scheduled__2024-02-12T20:30:00+00:00 [queued]>
[2024-02-12T21:13:12.534+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-02-12T21:13:12.554+0000] {taskinstance.py:2191} INFO - Executing <Task(HttpSensor): weather_api_ready> on 2024-02-12 20:30:00+00:00
[2024-02-12T21:13:12.562+0000] {standard_task_runner.py:60} INFO - Started process 64 to run task
[2024-02-12T21:13:12.569+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'weather_api_ready', 'scheduled__2024-02-12T20:30:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/Weather_dag.py', '--cfg-path', '/tmp/tmpsd2txnkx']
[2024-02-12T21:13:12.573+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask weather_api_ready
[2024-02-12T21:13:12.687+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.weather_api_ready scheduled__2024-02-12T20:30:00+00:00 [running]> on host 3bd3b2605e24
[2024-02-12T21:13:12.810+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T20:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T20:30:00+00:00'
[2024-02-12T21:13:12.813+0000] {http.py:130} INFO - Poking: /data/2.5/weather?q=Bangkok&appid=d69585a88935d2a759a90a77d406e260
[2024-02-12T21:13:12.826+0000] {base.py:83} INFO - Using connection ID 'weather_conn_id' for task execution.
[2024-02-12T21:13:13.081+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2024-02-12T21:13:13.099+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=weather_api_ready, execution_date=20240212T203000, start_date=20240212T211312, end_date=20240212T211313
[2024-02-12T21:13:13.142+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-12T21:13:13.200+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
