[2024-02-12T21:31:43.531+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.create_snowflake_database manual__2024-02-12T21:28:35.195233+00:00 [queued]>
[2024-02-12T21:31:43.555+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.create_snowflake_database manual__2024-02-12T21:28:35.195233+00:00 [queued]>
[2024-02-12T21:31:43.556+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-02-12T21:31:43.589+0000] {taskinstance.py:2191} INFO - Executing <Task(SnowflakeOperator): create_snowflake_database> on 2024-02-12 21:28:35.195233+00:00
[2024-02-12T21:31:43.601+0000] {standard_task_runner.py:60} INFO - Started process 81 to run task
[2024-02-12T21:31:43.607+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'create_snowflake_database', 'manual__2024-02-12T21:28:35.195233+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/Weather_dag.py', '--cfg-path', '/tmp/tmpq71e4j1a']
[2024-02-12T21:31:43.611+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask create_snowflake_database
[2024-02-12T21:31:43.748+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.create_snowflake_database manual__2024-02-12T21:28:35.195233+00:00 [running]> on host 3bd3b2605e24
[2024-02-12T21:31:44.238+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='create_snowflake_database' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T21:28:35.195233+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-12T21:28:35.195233+00:00'
[2024-02-12T21:31:44.242+0000] {sql.py:276} INFO - Executing: 
                    CREATE DATABASE IF NOT EXISTS Project ;
            
[2024-02-12T21:31:44.288+0000] {base.py:83} INFO - Using connection ID 'conn_id_snowflake' for task execution.
[2024-02-12T21:31:44.317+0000] {base.py:83} INFO - Using connection ID 'conn_id_snowflake' for task execution.
[2024-02-12T21:31:44.319+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2024-02-12T21:31:44.322+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-02-12T21:31:44.807+0000] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-02-12T21:31:44.905+0000] {cursor.py:1041} INFO - query execution done
[2024-02-12T21:31:44.907+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-12T21:31:44.908+0000] {sql.py:450} INFO - Running statement: CREATE DATABASE IF NOT EXISTS Project ;, parameters: None
[2024-02-12T21:31:44.910+0000] {cursor.py:1028} INFO - query: [CREATE DATABASE IF NOT EXISTS Project ;]
[2024-02-12T21:31:45.054+0000] {cursor.py:1041} INFO - query execution done
[2024-02-12T21:31:45.056+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-12T21:31:45.057+0000] {sql.py:459} INFO - Rows affected: 1
[2024-02-12T21:31:45.059+0000] {snowflake.py:400} INFO - Rows affected: 1
[2024-02-12T21:31:45.060+0000] {snowflake.py:401} INFO - Snowflake query id: 01b24f2b-3200-fe5c-0007-a44e00011396
[2024-02-12T21:31:45.061+0000] {cursor.py:1028} INFO - query: [COMMIT]
[2024-02-12T21:31:45.154+0000] {cursor.py:1041} INFO - query execution done
[2024-02-12T21:31:45.155+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-12T21:31:45.156+0000] {connection.py:718} INFO - closed
[2024-02-12T21:31:45.223+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2024-02-12T21:31:45.334+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=create_snowflake_database, execution_date=20240212T212835, start_date=20240212T213143, end_date=20240212T213145
[2024-02-12T21:31:45.401+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-12T21:31:45.497+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
